#!/usr/bin/env ruby

class Bootstrap
  def initialize
    detect_xpdf
    delete_old_jetty!
    generate_jetty
    symlink_configs
  end

  def detect_xpdf
    raise 'xpdf not detected. Please brew install it.' if `which pdftotext`.empty?
  end

  def delete_old_jetty!
    if Dir.exists?('jetty')
      system('rm -rf jetty')
    end
  end

  def generate_jetty
    system('rails g blacklight:jetty')
  end

  def symlink_configs
    configs = %w(jetty/solr/conf/solrconfig.xml jetty/solr/conf/schema.xml)
    configs.each do |f|
      system("mv #{f}\{,.bak}")
      source = File.expand_path(File.join('support', File.basename(f)))
      system("ln -s #{source} #{f}")
    end
  end
end

Bootstrap.new
