#!/bin/bash

set -e
ENVIRONMENT=$1
export RAILS_ENV=$1

if [ "$ENVIRONMENT" != "production" ]; then
  if [ "$ENVIRONMENT" != "staging" ]; then
    echo "Usage: ./script/deploy (staging|production)"
    exit 1
  fi
fi

echo "Switching to ${ENVIRONMENT} heroku remote"
if [ "$ENVIRONMENT" == "staging" ]; then
  APP_NAME=alicelaw-staging
  heroku maintenance:on --app $APP_NAME
  git push -f git@heroku.com:alicelaw-staging.git develop:master
else
  APP_NAME=alicelaw-production
  heroku maintenance:on --app $APP_NAME
  git push git@heroku.com:alicelaw-production.git master:master
fi

echo "Running heroku run rake db:migrate for ${APP_NAME}"
heroku run rake db:migrate --app $APP_NAME

echo "Running heroku restart for ${APP_NAME}"
heroku restart --app $APP_NAME

heroku maintenance:off --app $APP_NAME

echo "Grabbing website to wake up heroku"
curl "http://${APP_NAME}.herokuapp.com" &> /dev/null &
