#!/bin/bash

ENVIRONMENT=$1
export RAILS_ENV=$1

if [ "$ENVIRONMENT" != "production" ]; then
  if [ "$ENVIRONMENT" != "staging" ]; then
    echo "Usage: ./script/deploy (staging|production)"
    exit 1
  fi
fi

echo "Switching to ${ENVIRONMENT} heroku remote"
if [ "$ENVIRONMENT" == "staging" ]; then
  git push -f staging develop:master
  APP_NAME=alicelaw-staging
else
  git push heroku master:master
  APP_NAME=alicelaw-production
fi

echo "Running heroku rake db:migrate for ${APP_NAME}"
heroku rake db:migrate --app $APP_NAME

echo "Running heroku restart for ${APP_NAME}"
heroku restart --app $APP_NAME

echo "Grabbing website to wake up heroku"
curl "http://${APP_NAME}.heroku.com" &> /dev/null &
