require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubAreasController do

  # This should return the minimal set of attributes required to create a valid
  # SubArea. As you add validations to SubArea, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  let(:user) { FactoryGirl.create :user }

  describe "GET index" do
    it "assigns all sub_areas as @sub_areas" do
      sub_area = SubArea.create! valid_attributes
      get :index, {}
      assigns(:sub_areas).should eq([sub_area])
    end
  end

  describe "GET show" do
    it "assigns the requested sub_area as @sub_area" do
      sub_area = SubArea.create! valid_attributes
      get :show, {:id => sub_area.to_param}
      assigns(:sub_area).should eq(sub_area)
    end
  end

  describe "GET new" do
    context 'logged in' do
      it "assigns a new sub_area as @sub_area" do
        sign_in user
        get :new, {}
        response.should_not redirect_to(new_user_session_path)
        assigns(:sub_area).should be_a_new(SubArea)
      end
    end

    context 'logged out' do
      it "redirects to the login page" do
        get :new, {}
        response.should redirect_to(new_user_session_path)
      end
    end
  end

  describe "GET edit" do
    let(:sub_area) { SubArea.create! valid_attributes }

    context 'logged in' do
      it "assigns the requested sub_area as @sub_area" do
        sign_in user
        get :edit, {:id => sub_area.to_param}
        assigns(:sub_area).should eq(sub_area)
      end
    end

    context 'logged out' do
      it "redirects to the login page" do
        get :edit, {id: sub_area.to_param}
        response.should redirect_to(new_user_session_path)
      end
    end
  end

  describe "POST create" do
    context 'logged in' do
      before { sign_in user }

      describe "with valid params" do
        it "creates a new SubArea" do
          expect {
            post :create, {:sub_area => valid_attributes}
          }.to change(SubArea, :count).by(1)
        end

        it "assigns a newly created sub_area as @sub_area" do
          post :create, {:sub_area => valid_attributes}
          assigns(:sub_area).should be_a(SubArea)
          assigns(:sub_area).should be_persisted
        end

        it "redirects to the created sub_area" do
          post :create, {:sub_area => valid_attributes}
          response.should redirect_to(SubArea.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved sub_area as @sub_area" do
          # Trigger the behavior that occurs when invalid params are submitted
          SubArea.any_instance.stub(:save).and_return(false)
          post :create, {:sub_area => {}}
          assigns(:sub_area).should be_a_new(SubArea)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          SubArea.any_instance.stub(:save).and_return(false)
          post :create, {:sub_area => {}}
          response.should render_template("new")
        end
      end
    end

    context 'logged out' do
      it "redirects to the login page" do
        post :create, {sub_area: {}}
        response.should redirect_to(new_user_session_path)
      end
    end
  end

  describe "PUT update" do

    let(:sub_area) { SubArea.create! valid_attributes }
    context 'logged in' do
      before { sign_in user }
      describe "with valid params" do
        it "updates the requested sub_area" do
          # Assuming there are no other sub areas in the database, this
          # specifies that the SubArea created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          SubArea.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
          put :update, {:id => sub_area.to_param, :sub_area => {'these' => 'params'}}
        end

        it "assigns the requested sub_area as @sub_area" do
          put :update, {:id => sub_area.to_param, :sub_area => valid_attributes}
          assigns(:sub_area).should eq(sub_area)
        end

        it "redirects to the sub_area" do
          put :update, {:id => sub_area.to_param, :sub_area => valid_attributes}
          response.should redirect_to(sub_area)
        end
      end

      describe "with invalid params" do
        it "assigns the sub_area as @sub_area" do
          # Trigger the behavior that occurs when invalid params are submitted
          SubArea.any_instance.stub(:save).and_return(false)
          put :update, {:id => sub_area.to_param, :sub_area => {}}
          assigns(:sub_area).should eq(sub_area)
        end

        it "re-renders the 'edit' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          SubArea.any_instance.stub(:save).and_return(false)
          put :update, {:id => sub_area.to_param, :sub_area => {}}
          response.should render_template("edit")
        end
      end
    end

    context 'logged out' do
      it "redirects to the login page" do
        put :update, {:id => sub_area.to_param, :sub_area => {'these' => 'params'}}
        response.should redirect_to(new_user_session_path)
      end
    end
  end

  describe "DELETE destroy" do
    let!(:sub_area) { SubArea.create! valid_attributes }
    context 'logged in' do
      before { sign_in user }

      it "destroys the requested sub_area" do
        expect {
          delete :destroy, {:id => sub_area.to_param}
        }.to change(SubArea, :count).by(-1)
      end

      it "redirects to the sub areas list" do
        delete :destroy, {:id => sub_area.to_param}
        response.should redirect_to(sub_areas_url)
      end
    end

    context 'logged out' do
      it "redirects to the login page" do
        delete :destroy, {:id => sub_area.to_param}
        response.should redirect_to(new_user_session_path)
      end
    end
  end

end
