---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: staging
  domain: alicelaw.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-c1ae8eba
  image_type: m1.medium
  image_id: ami-3c994355
  security_groups:
  - alicelaw_staging_default
  - alicelaw_staging_web
  - alicelaw_staging_web_tools
  - alicelaw_staging_staging
  - alicelaw_staging_apache
  - alicelaw_staging_app
  - alicelaw_staging_passenger
  - alicelaw_staging_collectd
  - alicelaw_staging_common
  - alicelaw_staging_monit
  - alicelaw_staging_db
  - alicelaw_staging_postgresql
  - alicelaw_staging_postgresql_master
  - alicelaw_staging_elasticsearch
  - alicelaw_staging_examples
  - alicelaw_staging_graphite_server
  - alicelaw_staging_graphite_web
  - alicelaw_staging_graylog_elasticsearch
  - alicelaw_staging_graylog_mongodb
  - alicelaw_staging_mongodb
  - alicelaw_staging_graylog_server
  - alicelaw_staging_graylog_web
  - alicelaw_staging_haproxy
  external_host: ec2-107-21-175-89.compute-1.amazonaws.com
  external_ip: 107.21.175.89
  internal_host: ip-10-212-114-192.ec2.internal
  internal_ip: 10.212.114.192
  zone: us-east-1b
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
